import type { ProjectDetailResponse, ProjectResponse } from "@/api/types";

export const mockProject: ProjectResponse = {
  project_id: "project-1",
  name: "Tax return 2026",
  description: "Everything about this year's tax return",
  instructions: "Always answer in German and cite the paragraph.",
  sensitivity: "S1",
  status: "active",
  priority: "high",
  color: "#7c8cff",
  start_date: "2026-04-01",
  target_date: "2026-06-01",
  completed_date: null,
  task_count: 3,
  task_done_count: 1,
  knowledge_count: 1,
  chat_count: 2,
  next_due_task: "File the return (2026-05-31)",
  created_at: "2026-04-05T08:00:00Z",
  updated_at: "2026-04-06T08:00:00Z",
};

export const mockProjectDetail: ProjectDetailResponse = {
  ...mockProject,
  tasks: [
    {
      task_id: "t1",
      project_id: "project-1",
      name: "Collect receipts",
      description: null,
      status: "open",
      priority: "medium",
      due_date: null,
      sort_order: 0,
      created_at: "2026-04-05T09:00:00Z",
      updated_at: "2026-04-05T09:00:00Z",
    },
    {
      task_id: "t2",
      project_id: "project-1",
      name: "Open an account",
      description: null,
      status: "done",
      priority: "low",
      due_date: null,
      sort_order: 1,
      created_at: "2026-04-05T09:00:00Z",
      updated_at: "2026-04-05T09:00:00Z",
    },
  ],
  notes: [
    {
      note_id: "n1",
      project_id: "project-1",
      content: "The deadline moved to the end of May.",
      source: "user",
      created_at: "2026-04-05T10:00:00Z",
    },
  ],
  files: [
    {
      file_id: "f1",
      project_id: "project-1",
      filename: "stored-file.pdf",
      original_name: "contract.pdf",
      content_type: "application/pdf",
      size_bytes: 2048,
      extract_status: "ok",
      text_chars: 4200,
      created_at: "2026-04-05T11:00:00Z",
    },
    {
      file_id: "f2",
      project_id: "project-1",
      filename: "stored-scan.png",
      original_name: "scan.png",
      content_type: "image/png",
      size_bytes: 40960,
      extract_status: "unsupported",
      text_chars: 0,
      created_at: "2026-04-05T11:30:00Z",
    },
  ],
  links: [
    {
      link_id: "l1",
      project_id: "project-1",
      name: "Tax office",
      url: "https://example.com",
      created_at: "2026-04-05T11:00:00Z",
    },
  ],
  chats: [
    {
      conversation_id: "c1",
      title: "Which receipts count?",
      created_at: "2026-04-06T09:00:00Z",
      updated_at: "2026-04-06T09:30:00Z",
    },
  ],
};
